version: '3'

services:
  keycloak:
    image: 'quay.io/keycloak/keycloak:24.0.5'
    container_name: keycloak
    ports:
      - '8080:8080'
    volumes:
      - './imports:/opt/keycloak/data/import'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HTTPS_CLIENT_AUTH: request
      KC_HEALTH_ENABLED: true
    command:
      - start-dev
      - --import-realm
    extra_hosts:
    - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e \"GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3"]
      interval: 10s
      timeout: 5s
      retries: 5

  httpbin:
    container_name: httpbin
    image: mccutchen/go-httpbin:latest
    ports:
      - 9000:8080

  nginx:
    container_name: nginx
    restart: always
    image: nginx:alpine
    ports:
      - 8089:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
    - "host.docker.internal:host-gateway"
    depends_on:
      - oauth2-proxy
      - httpbin

  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    command:
      - --config=/oauth2-proxy.cfg
    restart: unless-stopped
    ports:
      - 4180:4180
    volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    depends_on:
      - keycloak
      - httpbin
